Update github action (#6)

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,22 +1,23 @@
-name: tests
+name: Lint and test
 
 on:
     push:
-        branches:
-            - develop
-            - main
+        branches: [ develop, main ]
     pull_request:
-        branches:
-            - develop
-            - main
+        types: [ opened, synchronize, reopened, ready_for_review ]
 
 permissions:
     contents: read
 
+concurrency:
+    group: ci-${{ github.ref }}
+    cancel-in-progress: true
+
 jobs:
     ci:
+        name: Lint and test
         runs-on: ubuntu-latest
-
+        if: "!github.event.pull_request.draft"
         steps:
             -   name: Checkout code
                 uses: actions/checkout@v7
@@ -34,6 +35,7 @@ jobs:
                 uses: actions/setup-node@v7
                 with:
                     node-version: '22'
+                    cache: 'npm'
 
             -   name: Setup Application
                 run: composer setup
@@ -43,10 +45,16 @@ jobs:
 
             -   name: Wait for Server
                 run: |
-                    for i in {1..30}; do
-                      curl -s http://127.0.0.1:8000 && break
-                      sleep 1
+                    for i in {1..5}; do
+                        if curl -f -s http://localhost:8000/health; then
+                            echo "Server is started successfully"
+                            exit 0
+                        fi
+                        echo "Waiting for server... ($i/5)"
+                        sleep 1
                     done
+                    echo "Error: Server failed to start within 5 seconds"
+                    exit 1
 
             -   name: Run CI Checks
                 run: composer ci:check
